/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["healthLive"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["healthReady"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Uso exclusivo del BFF; valida un ID token Auth0 y emite una sesión opaca. */
        post: operations["exchangeAuth0Session"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["revokeOwnSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["exportOwnAccount"];
        put?: never;
        post?: never;
        delete: operations["deleteOwnAccount"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listOwnNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/{notification_id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["markOwnNotificationRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateOwnProfile"];
        trace?: never;
    };
    "/api/v1/leagues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listOwnLeagues"];
        put?: never;
        post: operations["createLeague"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listOwnInvitations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leagues/{league_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getLeague"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leagues/{league_id}/competitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listLeagueCompetitions"];
        put?: never;
        post: operations["createCompetition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leagues/{league_id}/competitions/{competition_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCompetition"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leagues/{league_id}/competitions/{competition_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Fija de forma inmutable el calendario y las reglas vigentes. */
        post: operations["startCompetition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leagues/{league_id}/competitions/{competition_id}/portfolio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getOwnCompetitionPortfolio"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leagues/{league_id}/competitions/{competition_id}/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["submitCompetitionOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leagues/{league_id}/competitions/{competition_id}/reported-trades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Registra una ejecución simulada ya realizada; no envía una orden al mercado. */
        post: operations["reportCompetitionTrade"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leagues/{league_id}/competitions/{competition_id}/reported-trades/{execution_id}/corrections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Crea un movimiento compensatorio auditable; nunca modifica ni borra la ejecución original. */
        post: operations["correctReportedCompetitionTrade"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leagues/{league_id}/competitions/{competition_id}/orders/{order_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["cancelCompetitionOrder"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leagues/{league_id}/competitions/{competition_id}/ranking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCompetitionRanking"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leagues/{league_id}/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["inviteLeagueMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leagues/{league_id}/invitations/{invitation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["revokeLeagueInvitation"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invitations/{invitation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["acceptInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leagues/{league_id}/members/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["removeLeagueMember"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AccountExport: {
            /** @constant */
            schema_version: "1";
            user: {
                [key: string]: unknown;
            };
            profile: {
                [key: string]: unknown;
            } | null;
            memberships: {
                [key: string]: unknown;
            }[];
            invitations: {
                [key: string]: unknown;
            }[];
            notifications: components["schemas"]["Notification"][];
            financial_history: {
                [key: string]: unknown;
            }[];
            audit: {
                [key: string]: unknown;
            }[];
        };
        Notification: {
            id: string;
            kind: string;
            payload: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            created_at: string;
            read_at: string | null;
        };
        /** @enum {string} */
        Role: "owner" | "admin" | "member";
        /** @enum {string} */
        InvitationStatus: "pending" | "accepted" | "revoked" | "expired";
        LeagueMember: {
            user_id: string;
            display_name: string;
            role: components["schemas"]["Role"];
            /** Format: date-time */
            joined_at: string;
        };
        LeagueInvitation: {
            id: string;
            /** Format: email */
            email: string;
            role: components["schemas"]["Role"];
            /** Format: date-time */
            expires_at: string;
            status: components["schemas"]["InvitationStatus"];
        };
        LeagueDetail: {
            id: string;
            name: string;
            owner_id: string;
            /** Format: date-time */
            created_at: string;
            active: boolean;
            /** @enum {string} */
            plan: "free";
            actor_role: components["schemas"]["Role"];
            max_members: number;
            members: components["schemas"]["LeagueMember"][];
            /** @description Solo se devuelve a propietario o administrador. */
            invitations: components["schemas"]["LeagueInvitation"][];
        };
        OwnInvitation: {
            id: string;
            league_id: string;
            league_name: string;
            /** Format: date-time */
            expires_at: string;
        };
        CreatedInvitation: {
            id: string;
            /** Format: email */
            email: string;
            /** Format: date-time */
            expires_at: string;
            status: components["schemas"]["InvitationStatus"];
        };
        CompetitionInput: {
            name: string;
            /** Format: date-time */
            starts_at: string;
            /** Format: date-time */
            ends_at: string;
        };
        /** @enum {string} */
        CompetitionStatus: "draft" | "active" | "finished";
        /** @description Copia inmutable del calendario y reglas vigentes al iniciar. */
        RulesSnapshot: {
            version: string;
            calendar: {
                market: string;
                timezone: string;
                /** Format: date-time */
                starts_at: string;
                /** Format: date-time */
                ends_at: string;
            };
            rules: {
                /** @enum {string} */
                currency: "USD";
                initial_capital: string;
            } & {
                [key: string]: unknown;
            };
        };
        Competition: {
            id: string;
            league_id: string;
            name: string;
            /** Format: date-time */
            starts_at: string;
            /** Format: date-time */
            ends_at: string;
            status: components["schemas"]["CompetitionStatus"];
            rules_snapshot: components["schemas"]["RulesSnapshot"] | null;
            started_at: string | null;
        };
        OrderInput: {
            symbol: string;
            /** @enum {string} */
            side: "buy" | "sell";
            quantity: string;
            /** @enum {string} */
            order_type: "market" | "limit";
            allow_extended_hours: boolean;
            limit_price?: string | null;
            /** @description Comisión elegida por el usuario; si se omite se aplica la comisión fijada en rules_snapshot al ejecutarse. */
            commission?: string | null;
            client_order_id?: string | null;
        };
        Order: {
            id: string;
            symbol: string;
            /** @enum {string} */
            side: "buy" | "sell";
            quantity: string;
            /** @enum {string} */
            order_type: "market" | "limit";
            allow_extended_hours: boolean;
            limit_price: string | null;
            /** @enum {string} */
            status: "pending" | "filled" | "rejected" | "cancelled";
            rejection_reason: string | null;
            /** Format: date-time */
            submitted_at: string;
            commission: string | null;
        };
        Execution: {
            id: string;
            order_id: string;
            symbol: string;
            /** @enum {string} */
            side: "buy" | "sell";
            quantity: string;
            price: string;
            commission: string;
            /** @enum {string} */
            session: "regular" | "extended";
            /** Format: date-time */
            executed_at: string;
            /** @enum {string} */
            source: "fixture" | "reported";
            total_amount: string | null;
            /** @enum {string} */
            currency: "USD";
            fx_rate: string;
            correction_of: string | null;
        };
        Position: {
            symbol: string;
            quantity: string;
            price: string | null;
            market_value: string | null;
        };
        Portfolio: {
            id: string;
            competition_id: string;
            user_id: string;
            /** @enum {string} */
            currency: "USD";
            initial_cash: string;
            cash: string;
            /** Format: date-time */
            joined_at: string;
            joined_late: boolean;
            positions: components["schemas"]["Position"][];
            orders: components["schemas"]["Order"][];
            executions: components["schemas"]["Execution"][];
            equity: string;
            cumulative_return: string;
        };
        ReportedTradeInput: {
            /** @description Fecha y hora local; si no incluye offset se interpreta con timezone. */
            date: string;
            /**
             * @default Europe/Madrid
             * @enum {string}
             */
            timezone: "Europe/Madrid" | "UTC";
            ticker: string;
            /** @enum {string} */
            type: "buy" | "sell";
            quantity: string;
            price_per_share: string;
            total_amount: string;
            /** @description Opcional; si se omite se infiere del precio, cantidad, tipo e importe total. */
            commission?: string | null;
            /** @enum {string} */
            currency: "USD";
            fx_rate: string;
            client_trade_id: string;
        };
        ReportedTradeCorrectionInput: {
            /** Format: date-time */
            date: string;
            client_trade_id: string;
        };
        RankingRow: {
            rank: number;
            user_id: string;
            portfolio_id: string;
            display_name: string;
            cumulative_return: string;
            joined_late: boolean;
        };
        Ranking: {
            competition_id: string;
            /** Format: date-time */
            as_of: string;
            rows: components["schemas"]["RankingRow"][];
            digest: string;
        };
    };
    responses: {
        /** @description Sesión inválida o acción no autorizada */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
    };
    parameters: {
        LeagueId: string;
        CompetitionId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthLive: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Proceso ASGI operativo */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    healthReady: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dependencias disponibles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Alguna dependencia no está disponible */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    exchangeAuth0Session: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    id_token: string;
                    nonce: string;
                };
            };
        };
        responses: {
            /** @description Sesión propia emitida al BFF */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        session_token: string;
                        expires_in: number;
                    };
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    revokeOwnSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sesión revocada */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
        };
    };
    exportOwnAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Exportación completa y reproducible de datos propios, sin sesiones ni credenciales */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountExport"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    deleteOwnAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @constant */
                    confirm_account_deletion: true;
                };
            };
        };
        responses: {
            /** @description Cuenta eliminada */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Falta confirmación explícita */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Forbidden"];
        };
    };
    listOwnNotifications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Notificaciones privadas de la sesión, nuevas primero */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Notification"][];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    markOwnNotificationRead: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notification_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Notificación propia marcada como leída de forma idempotente */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Notification"];
                };
            };
            /** @description Notificación inexistente o ajena */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateOwnProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    display_name: string;
                    /** @enum {string} */
                    locale: "es" | "en";
                    /** Format: date */
                    birth_date: string;
                    /** Format: date-time */
                    accepted_terms_at: string;
                };
            };
        };
        responses: {
            /** @description Perfil actualizado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Perfil o política de edad inválidos */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listOwnLeagues: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ligas de las que forma parte la sesión */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeagueDetail"][];
                };
            };
        };
    };
    createLeague: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                };
            };
        };
        responses: {
            /** @description Liga creada */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeagueDetail"];
                };
            };
            /** @description Límite del plan alcanzado */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listOwnInvitations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Invitaciones pendientes ligadas al email de la sesión */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OwnInvitation"][];
                };
            };
        };
    };
    getLeague: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                league_id: components["parameters"]["LeagueId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Liga autorizada con miembros e invitaciones visibles por rol */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeagueDetail"];
                };
            };
            /** @description No existe o la sesión no pertenece a ella */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listLeagueCompetitions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                league_id: components["parameters"]["LeagueId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Competiciones de una liga accesible para la sesión */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Competition"][];
                };
            };
            /** @description Liga no accesible */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createCompetition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                league_id: components["parameters"]["LeagueId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompetitionInput"];
            };
        };
        responses: {
            /** @description Borrador de competición creado por propietario o administrador */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Competition"];
                };
            };
            /** @description Calendario inválido */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Liga no accesible */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCompetition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                league_id: components["parameters"]["LeagueId"];
                competition_id: components["parameters"]["CompetitionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Competición de una liga accesible para la sesión */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Competition"];
                };
            };
            /** @description Liga o competición no accesible */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    startCompetition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                league_id: components["parameters"]["LeagueId"];
                competition_id: components["parameters"]["CompetitionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Competición iniciada con rules_snapshot inmutable */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Competition"];
                };
            };
            /** @description Liga o competición no accesible */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description La competición ya estaba iniciada */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getOwnCompetitionPortfolio: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                league_id: components["parameters"]["LeagueId"];
                competition_id: components["parameters"]["CompetitionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cartera propia, posiciones e historial financiero */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Portfolio"];
                };
            };
            /** @description Liga */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    submitCompetitionOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                league_id: components["parameters"]["LeagueId"];
                competition_id: components["parameters"]["CompetitionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderInput"];
            };
        };
        responses: {
            /** @description Orden aceptada y cartera resultante */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Portfolio"];
                };
            };
            /** @description Orden inválida */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Liga */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Fuera de calendario o clave idempotente en conflicto */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    reportCompetitionTrade: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                league_id: components["parameters"]["LeagueId"];
                competition_id: components["parameters"]["CompetitionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportedTradeInput"];
            };
        };
        responses: {
            /** @description Operación declarada registrada atómicamente y cartera resultante */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Portfolio"];
                };
            };
            /** @description Campos */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Liga */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Fecha */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    correctReportedCompetitionTrade: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                league_id: components["parameters"]["LeagueId"];
                competition_id: components["parameters"]["CompetitionId"];
                execution_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportedTradeCorrectionInput"];
            };
        };
        responses: {
            /** @description Movimiento compensatorio creado y cartera resultante */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Portfolio"];
                };
            };
            /** @description Liga */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Corrección duplicada */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cancelCompetitionOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                league_id: components["parameters"]["LeagueId"];
                competition_id: components["parameters"]["CompetitionId"];
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Orden pendiente cancelada y cartera resultante */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Portfolio"];
                };
            };
            /** @description Liga */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description La orden ya no está pendiente */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCompetitionRanking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                league_id: components["parameters"]["LeagueId"];
                competition_id: components["parameters"]["CompetitionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ranking porcentual reproducible de participantes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ranking"];
                };
            };
            /** @description Liga o competición no accesible */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    inviteLeagueMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                league_id: components["parameters"]["LeagueId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                };
            };
        };
        responses: {
            /** @description Enlace de invitación creado; caduca a los siete días */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedInvitation"];
                };
            };
            /** @description Liga no accesible */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Límite del plan alcanzado */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    revokeLeagueInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                league_id: components["parameters"]["LeagueId"];
                invitation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Invitación revocada */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Liga o invitación no accesible */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    acceptInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invitation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Membresía creada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invitación no utilizable por esta sesión */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    removeLeagueMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                league_id: components["parameters"]["LeagueId"];
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Miembro expulsado conservando historial */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Liga no accesible */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
