"""Contratos de repositorios y unidad de trabajo de la aplicación."""

from __future__ import annotations

from contextlib import AbstractContextManager
from datetime import datetime
from typing import Protocol

from tradearena.application.models import (
    Competition, Invitation, League, Membership, Profile, TradingAccount, User,
)
from tradearena.domain.ranking import RankingSnapshot


class StoreConflict(RuntimeError):
    """Una restricción transaccional rechazó una escritura concurrente."""

    def __init__(self, constraint: str | None = None) -> None:
        super().__init__(constraint or "store_conflict")
        self.constraint = constraint


class UserRepository(Protocol):
    def get(self, user_id: str, *, for_update: bool = False) -> User | None: ...
    def get_by_identity(self, provider: str, subject: str) -> User | None: ...
    def get_by_email(self, email: str) -> User | None: ...
    def add(self, user: User) -> None: ...
    def save(self, user: User) -> None: ...
    def link_identity(
        self, provider: str, subject: str, user_id: str, email_verified: bool
    ) -> None: ...
    def delete_identities(self, user_id: str) -> None: ...


class ProfileRepository(Protocol):
    def get(self, user_id: str) -> Profile | None: ...
    def save(self, profile: Profile) -> None: ...
    def delete(self, user_id: str) -> None: ...


class SessionRepository(Protocol):
    def get(self, token_hash: str) -> tuple[str, datetime] | None: ...
    def add(
        self, token_hash: str, user_id: str, created_at: datetime, expires_at: datetime
    ) -> None: ...
    def revoke(self, token_hash: str, revoked_at: datetime) -> None: ...
    def revoke_for_user(self, user_id: str, revoked_at: datetime) -> None: ...


class LeagueRepository(Protocol):
    def get(self, league_id: str, *, for_update: bool = False) -> League | None: ...
    def add(self, league: League) -> None: ...
    def list_for_user(self, user_id: str) -> list[League]: ...
    def count_active_free_owned(self, owner_id: str) -> int: ...


class MembershipRepository(Protocol):
    def get(self, league_id: str, user_id: str) -> Membership | None: ...
    def save(self, membership: Membership) -> None: ...
    def list_for_user(self, user_id: str) -> list[Membership]: ...
    def list_active_for_league(self, league_id: str) -> list[Membership]: ...
    def count_active(self, league_id: str) -> int: ...
    def remove_active_for_user(self, user_id: str, removed_at: datetime) -> None: ...


class InvitationRepository(Protocol):
    def get(self, invitation_id: str) -> Invitation | None: ...
    def save(self, invitation: Invitation) -> None: ...
    def list_for_email(self, email: str) -> list[Invitation]: ...
    def list_pending_for_email(
        self, email: str, now: datetime
    ) -> list[Invitation]: ...
    def list_for_league(self, league_id: str) -> list[Invitation]: ...
    def count_pending(self, league_id: str, now: datetime) -> int: ...


class CompetitionRepository(Protocol):
    def get(
        self, competition_id: str, *, for_update: bool = False
    ) -> Competition | None: ...
    def add(self, competition: Competition) -> None: ...
    def save(self, competition: Competition) -> None: ...
    def list_for_league(self, league_id: str) -> list[Competition]: ...


class TradingRepository(Protocol):
    def get(
        self, competition_id: str, user_id: str, *, for_update: bool = False,
    ) -> TradingAccount | None: ...
    def add(self, account: TradingAccount) -> None: ...
    def save(self, account: TradingAccount) -> None: ...
    def list_for_competition(self, competition_id: str) -> list[TradingAccount]: ...
    def save_ranking(self, snapshot: RankingSnapshot) -> None: ...
    def latest_ranking(self, competition_id: str) -> RankingSnapshot | None: ...


class AuditRepository(Protocol):
    def add(
        self, occurred_at: datetime, actor_id: str | None, action: str,
        resource_type: str, resource_id: str, metadata: dict[str, str] | None = None,
    ) -> None: ...


class UnitOfWork(Protocol):
    users: UserRepository
    profiles: ProfileRepository
    sessions: SessionRepository
    leagues: LeagueRepository
    memberships: MembershipRepository
    invitations: InvitationRepository
    competitions: CompetitionRepository
    trading: TradingRepository
    audit: AuditRepository


class Store(Protocol):
    def transaction(self) -> AbstractContextManager[UnitOfWork]: ...
    def ready(self) -> bool: ...
